#!/bin/sh

TARGET="${HOME}/Desktop"

SIZES='
16,16x16
32,16x16@2x
32,32x32
64,32x32@2x
128,128x128
256,128x128@2x
256,256x256
512,256x256@2x
512,512x512
1024,512x512@2x
'

for SVG in "$@"; do
  if [ -e "$SVG" ]; then
    BASE=$(basename "$SVG" | sed 's/\.[^\.]*$//')
    ICONSET="$BASE.iconset"
    mkdir -p "${TARGET}/${ICONSET}"
    #shellcheck disable=2086
    for PARAMS in $SIZES; do
      SIZE=$( echo $PARAMS | cut -d, -f1)
      LABEL=$(echo $PARAMS | cut -d, -f2)
      case "${LABEL}" in
            *@2x)  DPI=144;;
            *   )  DPI=72 ;;
      esac
      rsvg-convert  --dpi-x="$DPI"  --dpi-y="$DPI"  --width="$SIZE"  --height="$SIZE"  --format='png'  --output "${TARGET}/${ICONSET}/icon_${LABEL}.png"  "${SVG}"
    # rsvg-convert from GNOME Project’s librsvg —— brew install librsvg
    done
    iconutil -c icns -o "${TARGET}/${BASE}.icns"  "${TARGET}/${ICONSET}"
  fi
done
exit

