#!/bin/sh -x

TARGET="${HOME}/Desktop/"

SIZES='
16,16x16
32,16x16@2x
32,32x32
64,32x32@2x
128,128x128
256,128x128@2x
256,256x256
512,256x256@2x
512,512x512
1024,512x512@2x
'

for SVG in "$@"; do
  BASE=$(basename "$SVG" | sed 's/\.[^\.]*$//')
  ICONSET="$BASE.iconset"
  mkdir -p "${TARGET}/$ICONSET"
  for PARAMS in $SIZES; do
    SIZE=$( echo $PARAMS | cut -d, -f1)
    LABEL=$(echo $PARAMS | cut -d, -f2)
    case "${LABEL}" in
          *@2x)  DPI=144;;
          *   )  DPI=72 ;;
    esac
    rsvg-convert  --dpi-x="$DPI"  --dpi-y="$DPI"  --width="$SIZE"  --height="$SIZE"  --format='png'  \
      --output "${TARGET}/${ICONSET}/icon_${LABEL}.png"  "${SVG}"
  done
done
iconutil -c icns -o "${TARGET}/${BASE}.icns"  "${TARGET}/${ICONSET}"
exit

          # sips  --setProperty dpiHeight "$DPI"  --setProperty dpiWidth "$DPI"  "./${ICONSET}/icon_${LABEL}.png"
          # svg2png  -h "$SIZE" -w "$SIZE"  "$SVG"  1> "${ICONSET}/icon_$LABEL.png" ## brew install svg2png
          # qlmanage  -t  -s "$SIZE"  -o .  "$SVG"                         ## using Gapplin QLgen
          # mv "$SIZE.svg.png"  "${HOME}/Desktop/${BASE}./icon_${LABEL}.png"
